DROP SCHEMA IF EXISTS WOQUIZ;
CREATE SCHEMA WOQUIZ;

CREATE TABLE WOQUIZ.WOQUIZ_USER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE WOQUIZ.BASE_ENTITY (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES WOQUIZ_USER(ID)
);

CREATE TABLE WOQUIZ.WORD (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    BASIC_WORD VARCHAR(255) NOT NULL,
    TRANSLATION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    LEVEL VARCHAR(255) NOT NULL,
    NR_ASKED INTEGER NOT NULL DEFAULT 0,
    NR_GOOD_ANSWERS INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (ID) REFERENCES BASE_ENTITY(ID)
);

CREATE TABLE WOQUIZ.QUIZ (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    SCORE INTEGER NOT NULL,
    ATTEMPT_DATE DATE NOT NULL,
    FOREIGN KEY (ID) REFERENCES BASE_ENTITY(ID)
);

CREATE TABLE  WOQUIZ.QUIZ_WORDS (
  QUIZZ_ID INTEGER NOT NULL,
  WORD_ID INTEGER NOT NULL,
  PRIMARY KEY (QUIZZ_ID, WORD_ID),
  FOREIGN KEY (QUIZZ_ID) REFERENCES QUIZ(ID),
  FOREIGN KEY (WORD_ID) REFERENCES WORD(ID)
);

CREATE TABLE WOQUIZ.ANSWER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    WORD_ID INTEGER NOT NULL,
    ANSWER VARCHAR(255) NOT NULL,
    RESULT BOOLEAN NOT NULL DEFAULT FALSE,
    QUIZ_ID INTEGER NOT NULL,
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ(ID),
    FOREIGN KEY (ID) REFERENCES BASE_ENTITY(ID),
    FOREIGN KEY (WORD_ID) REFERENCES WORD(ID)
);

CREATE TABLE WOQUIZ.WORD_HISTORY (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    QUIZ_ID INTEGER NOT NULL,
    ANSWER_ID INTEGER NOT NULL,
    FOREIGN KEY (ID) REFERENCES BASE_ENTITY(ID),
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZ(ID),
    FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER(ID)
);